version: 0.2

phases:
  install:
    commands:
      # Fetch the unique SHA for tagging Docker images
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $REGION_ID | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION_ID.amazonaws.com

  build:
    commands:
      - echo Build started for commit $IMAGE_TAG
      - echo Building the Docker image...
      - docker build -t $IMAGE_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed for commit $IMAGE_TAG
      - echo Pushing the Docker image to ECR...
      - docker push $ECR_REPOSITORY_URI:$IMAGE_TAG

      # Check if the Lambda function exists to update or create it
      - echo "Running the custom shell script..."
      # - chmod +x scripts/create_or_update_lambda_function.sh   # Ensure the script is executable
      # - ./scripts/create_or_update_lambda_function.sh     
env:
  exported-variables:
    - IMAGE_TAG