Parameters:
  ProjectName:
    Type: String
    Description: The name of the CodeBuild project
    Default: todos
  IsServerless:
    Type: String
    Description: Whether the application is serverless or not
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
  ImageTag:
    Type: String
    Description: The tag for the Docker image
    Default: latest
  ContainerImageRepositoryUri:
    Type: String
    Description: The URI of the ECR repository

Resources:

  MyS3Bucket:
    Type: AWS::S3::Bucket


Outputs:
  S3BucketName:
    Value: !Ref MyS3Bucket
    Export:
      Name: !Sub '${ProjectName}-s3-bucket-name-${AWS::Region}'