Parameters:
  ProjectName:
    Type: String
    Description: The name of the CodeBuild project
    Default: todos
  IsServerless:
    Type: String
    Description: Whether the application is serverless or not
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
  ImageTag:
    Type: String
    Description: The tag for the Docker image
    Default: latest
  ContainerImageRepositoryUri:
    Type: String
    Description: The URI of the ECR repository

Resources:

  FrontendS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-frontend-${AWS::AccountId}'

  FrontendS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser: !GetAtt FrontendS3BucketOAIP.S3CanonicalUserId
            Action: 's3:GetObject'
            Resource: !Sub '${FrontendS3Bucket.Arn}/*'

  FrontendS3BucketOAIP:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'OAI for ${ProjectName}'

  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt FrontendS3Bucket.RegionalDomainName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${FrontendS3BucketOAIP}'
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        PriceClass: PriceClass_100


  UserPool:
    Type: AWS::Cognito::UserPool
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      UserPoolName: !Sub '${ProjectName}-user-pool-${AWS::AccountId}'
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
      Schema:
        - Name: email
          Required: true
          Mutable: true
        - Name: name
          Required: true
          Mutable: true
  
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub '${ProjectName}-user-pool-client-${AWS::AccountId}'
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_USER_AUTH
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - !Sub 'https://${CloudfrontDistribution.DomainName}'
      LogoutURLs:
        - !Sub 'https://${CloudfrontDistribution.DomainName}'
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - phone
  
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub '${ProjectName}-domain'
      UserPoolId: !Ref UserPool

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TableName: !Sub '${ProjectName}-todos-${AWS::AccountId}'
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt LambdaExecutionRole.Arn
      FunctionName: !Sub '${ProjectName}-lambda-${AWS::AccountId}'
      PackageType: Image
      Code:
        ImageUri: !Sub '${ContainerImageRepositoryUri}:${ImageTag}'
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DynamoDBTable
          REGION: !Ref 'AWS::Region'

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource: '*'
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: !GetAtt DynamoDBTable.Arn
  
  LamdbaFunctionInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${APIGateway}/*'

  APIGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Sub '${ProjectName}-api-${AWS::AccountId}'
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - !Sub 'https://${CloudfrontDistribution.DomainName}'
        AllowMethods:
          - '*'
        AllowHeaders:
          - '*'
      Target: !GetAtt LambdaFunction.Arn
      
  APIGatewayAuthorizer:
    Type: AWS::ApiGatewayV2::Authorizer
    Properties:
      ApiId: !Ref APIGateway
      AuthorizerType: JWT
      IdentitySource:
        - '$request.header.Authorization'
      JwtConfiguration:
        Audience:
          - !Ref UserPoolClient
        Issuer: !Sub 'https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}'
      Name: !Sub '${ProjectName}-authorizer-${AWS::AccountId}'

  APIGatewayDefaultRouteOverrides:
    Type: AWS::ApiGatewayV2::ApiGatewayManagedOverrides
    Properties: 
      ApiId: !Ref APIGateway
      Route: 
        AuthorizationType: JWT
        AuthorizerId: !Ref APIGatewayAuthorizer

  APIGatewayOptionsRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref APIGateway
      RouteKey: OPTIONS /{proxy+}
      Target: !Sub 'integrations/${APIGateway}'


Outputs:
  S3BucketFrontend:
    Value: !Ref FrontendS3Bucket
    Export:
      Name: 'S3BucketFrontend'
  RedirectURI:
    Value: !Sub 'https://${CloudfrontDistribution.DomainName}'
    Export:
      Name: 'RedirectURI'
  UserPoolID:
    Value: !Ref UserPool
    Export:
      Name: 'UserPoolID'
  UserPoolDomain:
    Value: !Ref UserPoolDomain
    Export:
      Name: 'UserPoolDomain'
  ClientID:
    Value: !Ref UserPoolClient
    Export:
      Name: 'ClientID'
  APIGatewayEndpoint:
    Value: !GetAtt APIGateway.ApiEndpoint
    Export:
      Name: 'APIGatewayEndpoint'