Parameters:
  ProjectName:
    Type: String
    Description: The name of the CodeBuild project
    Default: todos
  IsServerless:
    Type: String
    Description: Whether the application is serverless or not
    Default: "true"
  ImageTag:
    Type: String
    Description: The tag for the Docker image
    Default: latest
  ContainerImageRepositoryUri:
    Type: String
    Description: The URI of the ECR repository

Resources:

  MyS3Bucket:
    Type: AWS::S3::Bucket